<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Gum.MonoGame" />
		<PackageReference Include="MonoGame.Framework.Native">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
	</ItemGroup>
</Project>