<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.companyname.DungeonSlime.Android</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <RootNamespace>DungeonSlime.Android</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" />
    <PackageReference Include="MonoGame.Framework.Android" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MonoGameLibrary\MonoGameLibrary.csproj" />
	</ItemGroup>
</Project>